import type { Metadata } from 'next'
import localFont from 'next/font/local';
import { cn } from '@/lib/utils';
import './globals.css'

const headingFont = localFont({
  src: "../public/fonts/SCDream4.otf"
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("h-full", headingFont.className)}>{children}</body>
    </html>
  );
}
